import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const prisma = new PrismaClient({ adapter } as any);

const stipendier = [
  // ── TEKNIK & INGENJÖR ──────────────────────────────────────────────
  {
    namn: "Nils Ericsons stipendium",
    organisation: "Svenska Väg- och Vattenbyggares Riksförbund",
    beskrivning: "Stipendium för studenter inom väg- och vattenbyggnad med goda studieresultat.",
    belopp: 20000, deadline: new Date("2026-10-01"),
    kategorier: ["teknik", "ingenjör", "infrastruktur"],
    målgrupp: ["student", "civilingenjör"],
    url: "https://svr.se",
  },
  {
    namn: "Adlerbertska stipendierna",
    organisation: "Chalmers tekniska högskola",
    beskrivning: "Stipendier till studenter vid Chalmers med goda studieresultat och ekonomiska behov.",
    belopp: 10000, beloppMax: 30000, deadline: new Date("2026-11-30"),
    kategorier: ["teknik", "Chalmers"],
    målgrupp: ["student", "civilingenjör"],
    url: "https://chalmers.se/stipendier",
  },
  {
    namn: "KTH:s stipendier",
    organisation: "Kungliga Tekniska Högskolan",
    beskrivning: "Olika stipendier för studenter på KTH – baserade på meriter och ekonomiska behov.",
    belopp: 10000, beloppMax: 40000, deadline: new Date("2026-10-15"),
    kategorier: ["teknik", "KTH"],
    målgrupp: ["student", "civilingenjör"],
    url: "https://kth.se/stipendier",
  },
  {
    namn: "Sven och Dagmar Saléns stiftelse",
    organisation: "Sven och Dagmar Saléns stiftelse",
    beskrivning: "Stipendier för studier eller forskning om sjöfart och marin teknik.",
    belopp: 20000, deadline: new Date("2026-08-31"),
    kategorier: ["sjöfart", "marin", "teknik"],
    målgrupp: ["student", "forskare"],
    url: "https://salenstiftelse.se",
  },
  {
    namn: "Kungliga Ingenjörsvetenskapsakademien – IVA",
    organisation: "IVA",
    beskrivning: "Stöder unga ingenjörers och teknikers forskning och innovation i Sverige.",
    belopp: 25000, beloppMax: 75000, deadline: new Date("2026-09-01"),
    kategorier: ["teknik", "innovation", "forskning"],
    målgrupp: ["civilingenjör", "forskare", "doktorand"],
    url: "https://iva.se",
  },
  // ── NATURVETENSKAP & MEDICIN ───────────────────────────────────────
  {
    namn: "Ahlmansfonden",
    organisation: "Ahlmansfonden",
    beskrivning: "Stöd till studerande från Malmöhus och Kristianstads län för studier inom teknik, naturvetenskap eller medicin.",
    belopp: 15000, beloppMax: 50000, deadline: new Date("2026-09-15"),
    kategorier: ["teknik", "naturvetenskap", "medicin", "Skåne"],
    målgrupp: ["student"],
    url: "https://ahlmansfonden.se",
  },
  {
    namn: "Märta Lundqvists stipendiefond",
    organisation: "Karolinska Institutet",
    beskrivning: "Stöder medicinska studenter och unga läkare med forskning inom klinisk medicin.",
    belopp: 30000, deadline: new Date("2026-10-31"),
    kategorier: ["medicin", "forskning", "klinisk"],
    målgrupp: ["student", "läkarstudent", "forskare"],
    url: "https://ki.se/stipendier",
  },
  {
    namn: "Cancerfondens forskningsstipendium",
    organisation: "Cancerfonden",
    beskrivning: "Finansierar cancerforskning på doktorand- och postdoktorsnivå i Sverige.",
    belopp: 350000, beloppMax: 700000, deadline: new Date("2026-11-01"),
    kategorier: ["medicin", "forskning", "cancer"],
    målgrupp: ["doktorand", "postdoktor", "forskare"],
    url: "https://cancerfonden.se/forskning",
  },
  {
    namn: "Hjärnfonden – Forskarstipendium",
    organisation: "Hjärnfonden",
    beskrivning: "Stöd till forskning om hjärnsjukdomar, neurologi och psykiatri.",
    belopp: 200000, deadline: new Date("2026-12-01"),
    kategorier: ["medicin", "neurologi", "forskning"],
    målgrupp: ["doktorand", "postdoktor", "forskare"],
    url: "https://hjarnfonden.se",
  },
  // ── FORSKNING & VETENSKAP ──────────────────────────────────────────
  {
    namn: "Hierta-Retzius stipendiefond",
    organisation: "Kungliga Vetenskapsakademien",
    beskrivning: "Till svenska vetenskapsmän och vetenskapskvinnor för vetenskapliga undersökningar.",
    belopp: 50000, deadline: new Date("2026-12-01"),
    kategorier: ["forskning", "vetenskap", "naturvetenskap"],
    målgrupp: ["forskare", "doktorand"],
    url: "https://kva.se",
  },
  {
    namn: "Stiftelsen Lars Hiertas Minne",
    organisation: "Stiftelsen Lars Hiertas Minne",
    beskrivning: "Stöder vetenskaplig forskning, kulturellt skapande och utbildning i Sverige.",
    belopp: 30000, beloppMax: 100000, deadline: new Date("2026-09-30"),
    kategorier: ["forskning", "kultur", "utbildning"],
    målgrupp: ["forskare", "doktorand", "student"],
    url: "https://hiertas-minne.se",
  },
  {
    namn: "Helge Ax:son Johnsons stiftelse",
    organisation: "Helge Ax:son Johnsons stiftelse",
    beskrivning: "Understöder vetenskaplig forskning, studier och kulturella ändamål.",
    belopp: 10000, beloppMax: 80000, deadline: new Date("2026-10-31"),
    kategorier: ["forskning", "vetenskap", "kultur"],
    målgrupp: ["forskare", "student"],
    url: null,
  },
  {
    namn: "Riksbankens Jubileumsfond – Sabbatical",
    organisation: "Riksbankens Jubileumsfond",
    beskrivning: "Sabbatical-anslag för forskning inom humaniora och samhällsvetenskap.",
    belopp: 500000, deadline: new Date("2026-09-15"),
    kategorier: ["humaniora", "samhällsvetenskap", "forskning"],
    målgrupp: ["forskare", "lektor", "professor"],
    url: "https://rj.se",
  },
  {
    namn: "Wallenbergstiftelsernas postdoktorsstipendium",
    organisation: "Knut och Alice Wallenbergs Stiftelse",
    beskrivning: "Finansierar postdoktoral forskning vid världsledande universitet utomlands.",
    belopp: 1500000, beloppMax: 2000000, deadline: new Date("2026-10-01"),
    kategorier: ["forskning", "internationell", "postdoktor"],
    målgrupp: ["postdoktor", "forskare"],
    url: "https://kaw.wallenberg.org",
  },
  {
    namn: "Vetenskapsrådets internationella postdok",
    organisation: "Vetenskapsrådet",
    beskrivning: "Stöd för svenska forskare att genomföra postdoktoral forskning utomlands.",
    belopp: 1200000, deadline: new Date("2026-01-15"),
    kategorier: ["forskning", "internationell", "postdoktor"],
    målgrupp: ["postdoktor", "forskare"],
    url: "https://vr.se",
  },
  // ── INTERNATIONELLT & UTBYTE ───────────────────────────────────────
  {
    namn: "Svenska Institutet – stipendier för studier i Sverige",
    organisation: "Svenska Institutet",
    beskrivning: "Stipendier för internationella studenter som läser masterprogram i Sverige.",
    belopp: 11000, deadline: new Date("2027-02-10"),
    kategorier: ["internationell", "master", "Sverige"],
    målgrupp: ["student", "masterstudent"],
    url: "https://si.se/stipendier",
  },
  {
    namn: "Erasmus+",
    organisation: "Europeiska Kommissionen",
    beskrivning: "EU:s program för utbildning, ungdom och sport – studier och praktik i Europa.",
    belopp: 500, beloppMax: 700, deadline: new Date("2027-03-31"),
    kategorier: ["EU", "utbyte", "praktik", "internationell"],
    målgrupp: ["student", "yrkesstudent"],
    url: "https://erasmus-plus.ec.europa.eu",
  },
  {
    namn: "Rotarys ungdomsstipendium",
    organisation: "Rotary Sverige",
    beskrivning: "Utbytesstipendium för ungdomar 15–19 år för ett skolår utomlands.",
    belopp: 0, deadline: new Date("2026-11-01"),
    kategorier: ["utbyte", "ungdom", "gymnasiet", "internationell"],
    målgrupp: ["gymnasieelev"],
    url: "https://rotary.se",
  },
  {
    namn: "Fulbright – American-Scandinavian Foundation",
    organisation: "American-Scandinavian Foundation",
    beskrivning: "Stipendier för studier och forskning i USA för skandinaver.",
    belopp: 150000, deadline: new Date("2026-10-15"),
    kategorier: ["USA", "internationell", "forskning", "utbyte"],
    målgrupp: ["student", "forskare", "doktorand"],
    url: "https://amscan.org",
  },
  {
    namn: "DAAD – Deutschlandstipendium",
    organisation: "Deutscher Akademischer Austauschdienst",
    beskrivning: "Stipendier för studier och forskning i Tyskland.",
    belopp: 25000, deadline: new Date("2026-11-30"),
    kategorier: ["Tyskland", "internationell", "utbyte"],
    målgrupp: ["student", "doktorand", "forskare"],
    url: "https://daad.de",
  },
  // ── HUMANIORA, KULTUR & SAMHÄLLE ───────────────────────────────────
  {
    namn: "Birgit och Gad Rausings Stiftelse",
    organisation: "Birgit och Gad Rausings Stiftelse",
    beskrivning: "Stöder forskning om europeisk och svensk historia, kultur och konst.",
    belopp: 100000, beloppMax: 500000, deadline: new Date("2026-10-01"),
    kategorier: ["humaniora", "historia", "kultur", "forskning"],
    målgrupp: ["forskare", "doktorand"],
    url: "https://rausingsstiftelse.se",
  },
  {
    namn: "Konstnärsnämndens stipendier",
    organisation: "Konstnärsnämnden",
    beskrivning: "Ettåriga och långtidsstipendier för professionella konstnärer inom alla konstformer.",
    belopp: 180000, deadline: new Date("2026-09-01"),
    kategorier: ["konst", "kultur", "kreativt"],
    målgrupp: ["konstnär", "kulturutövare"],
    url: "https://konstnarsnamnden.se",
  },
  {
    namn: "Sveriges Författarfonds stipendier",
    organisation: "Sveriges Författarfond",
    beskrivning: "Stöd till svenska skönlitterära och facklitterära författare.",
    belopp: 50000, beloppMax: 200000, deadline: new Date("2026-08-15"),
    kategorier: ["litteratur", "skrivande", "kultur"],
    målgrupp: ["författare", "kulturutövare"],
    url: "https://forfattarfonden.se",
  },
  {
    namn: "Stiftelsen Framtidens Kultur",
    organisation: "Stiftelsen Framtidens Kultur",
    beskrivning: "Stöder kulturprojekt och kulturskapare med fokus på nyskapande och mångfald.",
    belopp: 50000, beloppMax: 300000, deadline: new Date("2026-11-15"),
    kategorier: ["kultur", "kreativt", "mångfald"],
    målgrupp: ["kulturutövare", "konstnär"],
    url: "https://framtidenskultur.se",
  },
  // ── UTBILDNING & LÄRARE ────────────────────────────────────────────
  {
    namn: "Lärarnas Riksförbunds stipendium",
    organisation: "Lärarnas Riksförbund",
    beskrivning: "Stipendium för lärarstudenter och verksamma lärare för kompetensutveckling.",
    belopp: 15000, deadline: new Date("2026-04-30"),
    kategorier: ["lärare", "utbildning", "pedagogik"],
    målgrupp: ["lärare", "lärarstudent"],
    url: "https://lr.se",
  },
  {
    namn: "Skolporten – Forskningsstipendium",
    organisation: "Skolporten",
    beskrivning: "Stöder lärare och rektorer som vill bedriva forskning om skola och utbildning.",
    belopp: 50000, deadline: new Date("2026-12-15"),
    kategorier: ["lärare", "pedagogik", "forskning", "skola"],
    målgrupp: ["lärare", "rektor", "forskare"],
    url: "https://skolporten.se",
  },
  // ── EKONOMI & NÄRINGSLIV ───────────────────────────────────────────
  {
    namn: "Jan Wallanders och Tom Hedelius stiftelse",
    organisation: "Jan Wallanders och Tom Hedelius stiftelse",
    beskrivning: "Stöder forskning inom ekonomi och samhällsvetenskap vid svenska lärosäten.",
    belopp: 200000, beloppMax: 1000000, deadline: new Date("2026-10-15"),
    kategorier: ["ekonomi", "samhällsvetenskap", "forskning"],
    målgrupp: ["doktorand", "forskare", "postdoktor"],
    url: "https://handelsbanken.se/wallander",
  },
  {
    namn: "Handelsbankens stipendier – Juniorforskarstöd",
    organisation: "Svenska Handelsbanken",
    beskrivning: "Anslag för yngre forskare inom ekonomi, juridik och samhällsvetenskap.",
    belopp: 300000, deadline: new Date("2026-10-15"),
    kategorier: ["ekonomi", "juridik", "forskning"],
    målgrupp: ["doktorand", "postdoktor"],
    url: "https://handelsbanken.se/stipendier",
  },
  {
    namn: "Riksbankens Jubileumsfond – Infrastrukturprojekt",
    organisation: "Riksbankens Jubileumsfond",
    beskrivning: "Finansierar samhällsvetenskaplig och humanistisk forskning av hög kvalitet.",
    belopp: 500000, beloppMax: 3000000, deadline: new Date("2026-01-01"),
    kategorier: ["samhällsvetenskap", "humaniora", "forskning"],
    målgrupp: ["forskare", "professor", "lektor"],
    url: "https://rj.se",
  },
  // ── JURIDIK ────────────────────────────────────────────────────────
  {
    namn: "Advokatsamfundets stipendium",
    organisation: "Sveriges Advokatsamfund",
    beskrivning: "Stipendier för juridikstudenter för studier i utlandet eller forskning.",
    belopp: 30000, beloppMax: 60000, deadline: new Date("2026-09-30"),
    kategorier: ["juridik", "rättsvetenskap"],
    målgrupp: ["juriststudent", "student"],
    url: "https://advokatsamfundet.se",
  },
  // ── MILJÖ & HÅLLBARHET ─────────────────────────────────────────────
  {
    namn: "Formas – Forskningsrådet för miljö",
    organisation: "Formas",
    beskrivning: "Stöder forskning och innovation för hållbar samhällsutveckling.",
    belopp: 400000, beloppMax: 2000000, deadline: new Date("2026-11-06"),
    kategorier: ["miljö", "hållbarhet", "forskning", "klimat"],
    målgrupp: ["forskare", "doktorand"],
    url: "https://formas.se",
  },
  {
    namn: "Stiftelsen Sverigehälsan – Miljöstipendium",
    organisation: "Stiftelsen Sverigehälsan",
    beskrivning: "Stöder projekt och studier med inriktning på miljö och hållbar livsstil.",
    belopp: 15000, deadline: new Date("2026-10-01"),
    kategorier: ["miljö", "hållbarhet", "livsstil"],
    målgrupp: ["student", "kulturutövare"],
    url: null,
  },
  // ── SOCIALT & VÅRD ─────────────────────────────────────────────────
  {
    namn: "Sophiahemmets Högskola – Stipendier",
    organisation: "Sophiahemmets Högskola",
    beskrivning: "Stipendier för sjuksköterskestudenter och vårdpersonal i vidareutbildning.",
    belopp: 10000, deadline: new Date("2026-09-01"),
    kategorier: ["vård", "omvårdnad", "sjuksköterska"],
    målgrupp: ["student", "sjuksköterskestudent", "vårdpersonal"],
    url: "https://sophiahemmet.se",
  },
  {
    namn: "Socialstyrelsen – FoU-stöd",
    organisation: "Socialstyrelsen",
    beskrivning: "Stöd till forskning och utveckling inom socialtjänst och hälso- och sjukvård.",
    belopp: 200000, deadline: new Date("2026-12-01"),
    kategorier: ["socialt arbete", "vård", "forskning"],
    målgrupp: ["forskare", "socionomstudent"],
    url: "https://socialstyrelsen.se",
  },
  // ── IDROTT ─────────────────────────────────────────────────────────
  {
    namn: "Riksidrottsförbundets stipendier",
    organisation: "Riksidrottsförbundet",
    beskrivning: "Stöd till elitidrottare som kombinerar idrott med studier.",
    belopp: 25000, deadline: new Date("2026-08-31"),
    kategorier: ["idrott", "elit", "kombinationsstudier"],
    målgrupp: ["student", "elitidrottare"],
    url: "https://rf.se",
  },
  // ── JOURNALISTIK & MEDIA ───────────────────────────────────────────
  {
    namn: "Publicistklubbens stipendier",
    organisation: "Publicistklubben",
    beskrivning: "Stöd till journaliststudenter och yrkesverksamma journalister.",
    belopp: 20000, deadline: new Date("2026-10-01"),
    kategorier: ["journalistik", "media"],
    målgrupp: ["student", "journalist"],
    url: "https://publicistklubben.se",
  },
  {
    namn: "TU – Tidningsutgivarnas stipendier",
    organisation: "TU Medier i Sverige",
    beskrivning: "Bidrag för journalistikstudier och forskning om mediebranschen.",
    belopp: 15000, deadline: new Date("2026-11-01"),
    kategorier: ["journalistik", "media", "forskning"],
    målgrupp: ["student", "journalist", "forskare"],
    url: "https://tu.se",
  },
  // ── DIASPORA & MÅNGFALD ────────────────────────────────────────────
  {
    namn: "Mångkulturellt Centrum – stipendium",
    organisation: "Mångkulturellt centrum",
    beskrivning: "Stöder studenter och kulturutövare med utländsk bakgrund i Sverige.",
    belopp: 10000, beloppMax: 25000, deadline: new Date("2026-10-15"),
    kategorier: ["mångfald", "kultur", "integration"],
    målgrupp: ["student", "kulturutövare"],
    url: "https://mkc.botkyrka.se",
  },
  // ── GENERELLA STUDIER ──────────────────────────────────────────────
  {
    namn: "Centralförbundet för socialt arbete – CSA-stipendiet",
    organisation: "CSA",
    beskrivning: "Ges till studenter inom socialt arbete, folkhälsa eller samhällsvetenskap.",
    belopp: 15000, deadline: new Date("2026-09-15"),
    kategorier: ["socialt arbete", "folkhälsa", "samhällsvetenskap"],
    målgrupp: ["student"],
    url: "https://csa.nu",
  },
  {
    namn: "Röda Korsets stipendier",
    organisation: "Svenska Röda Korset",
    beskrivning: "Stöder studenter som vill arbeta med humanitärt arbete eller katastrofmedicin.",
    belopp: 12000, deadline: new Date("2026-09-01"),
    kategorier: ["humanitärt", "vård", "internationell"],
    målgrupp: ["student", "sjuksköterskestudent"],
    url: "https://redcross.se",
  },
  {
    namn: "Sida – Minor Field Studies",
    organisation: "Sida",
    beskrivning: "Stipendier för studenter som vill göra sitt examensarbete i ett låg- eller medelinkomstland.",
    belopp: 30000, deadline: new Date("2026-11-01"),
    kategorier: ["internationell", "bistånd", "examensarbete"],
    målgrupp: ["student", "masterstudent"],
    url: "https://sida.se/mfs",
  },
];

async function main() {
  console.log("Seeder: Raderar gamla stipendier...");
  await prisma.stipendium.deleteMany();
  console.log("Seeder: Skapar stipendier...");
  for (const s of stipendier) {
    await prisma.stipendium.create({ data: s });
  }
  console.log(`✅ Seedad ${stipendier.length} stipendier.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
